<?php

namespace ContainerG0uxzCP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateNewLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\GenerateNewLogin' shared autowired service.
     *
     * @return \App\Command\GenerateNewLogin
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateNewLogin.php';

        return $container->services['console.command.public_alias.App\\Command\\GenerateNewLogin'] = new \App\Command\GenerateNewLogin($container);
    }
}
