<?php

namespace ContainerG0uxzCP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LoginUser' shared autowired service.
     *
     * @return \App\Controller\LoginUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MyController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LoginUser.php';

        $container->services['App\\Controller\\LoginUser'] = $instance = new \App\Controller\LoginUser();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\LoginUser', $container));

        return $instance;
    }
}
