<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0scyJe\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0scyJe/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerL0scyJe.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerL0scyJe\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerL0scyJe\App_KernelTestDebugContainer([
    'container.build_hash' => 'L0scyJe',
    'container.build_id' => '419272b1',
    'container.build_time' => 1628841386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0scyJe');
