<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG0uxzCP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG0uxzCP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG0uxzCP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG0uxzCP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG0uxzCP\App_KernelDevDebugContainer([
    'container.build_hash' => 'G0uxzCP',
    'container.build_id' => '44b7bbe3',
    'container.build_time' => 1634808418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG0uxzCP');
