<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin_login' => [[], ['_controller' => 'App\\Controller\\AdminController::login'], [], [['text', '/admin/login']], [], []],
    'audiobooks_add' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::addAudiobook'], [], [['text', '/audiobooks/addAudiobook']], [], []],
    'audiobooks_get' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::getZipFile'], [], [['text', '/audiobooks/getAudiobook']], [], []],
    'sendZipFile' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::sendZipFile'], [], [['text', '/audiobooks/sendZipFile']], [], []],
    'removeAudiobook' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::removeAudiobook'], [], [['text', '/audiobooks/removeAudiobook']], [], []],
    'getJsonAudiobook' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::getJsonAudiobook'], [], [['text', '/audiobooks/getJsonAudiobook']], [], []],
    'editAudiobook' => [[], ['_controller' => 'App\\Controller\\AudiobooksActionsController::editAudiobook'], [], [['text', '/audiobooks/editAudiobook']], [], []],
    'audiobooks_gets' => [[], ['_controller' => 'App\\Controller\\AudiobooksSetsController::getSets'], [], [['text', '/audiobooks/getSets']], [], []],
    'add_audiobook_sets' => [[], ['_controller' => 'App\\Controller\\AudiobooksSetsController::addNewSet'], [], [['text', '/audiobooks/addSet']], [], []],
    'get_sets_data' => [[], ['_controller' => 'App\\Controller\\AudiobooksSetsController::getSetData'], [], [['text', '/audiobooks/getSetData']], [], []],
    'change_set_name' => [[], ['_controller' => 'App\\Controller\\AudiobooksSetsController::changeSetName'], [], [['text', '/audiobooks/changeSetName']], [], []],
    'delete_set' => [[], ['_controller' => 'App\\Controller\\AudiobooksSetsController::deleteSet'], [], [['text', '/audiobooks/deleteSet']], [], []],
    'user_login' => [[], ['_controller' => 'App\\Controller\\LoginUser::loginUser'], [], [['text', '/user/login']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/user/register']], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], []],
    'user_info' => [[], ['_controller' => 'App\\Controller\\UsersActionsController::userInfo'], [], [['text', '/admin/users']], [], []],
    'user_edit' => [[], ['_controller' => 'App\\Controller\\UsersActionsController::userEdit'], [], [['text', '/admin/users/edit']], [], []],
    'user_delete' => [[], ['_controller' => 'App\\Controller\\UsersActionsController::userDelete'], [], [['text', '/admin/users/delete']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
];
